"""removed date col from Reading table

Revision ID: 3d236c9d2e2d
Revises: c9f2bbf57965
Create Date: 2024-10-20 15:46:19.155313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d236c9d2e2d'
down_revision: Union[str, None] = 'c9f2bbf57965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('Date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
