"""add date col from Reading table

Revision ID: e8fa8dad1a57
Revises: fafd7d29ab54
Create Date: 2024-10-20 16:35:20.075748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8fa8dad1a57'
down_revision: Union[str, None] = 'fafd7d29ab54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('Date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'Date')
    # ### end Alembic commands ###
